version: "3.7"
services:
  deployer:
    image: iknowcss/iknowcss-deploy:latest
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws
    env_file:
      - .env
    working_dir: /app
    entrypoint: tail -f /dev/null
  data-updater:
    build:
      context: ./doh-data-ingest
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./doh-data-ingest:/app
      - $HOME/.aws:/root/.aws
